### ISSUE TITLE
Regression test mode

### ISSUE THREAD

**Issue by nodestory** [bitmark-inc/bitmarkd#101]
There are 3 supported chains in bitmarkd configuration: `bitmark`, `testing`, and `local`. The local chain is designed for running regression tests.

The current local chain doesn't support generating blocks on demand for testing purposes. Almost every test case is coupled with recorderd, which makes the regression tests time-consuming. Most of the time is spent in checking if recorderd is working. The local chain should enable developers to have full control over the environment and test the bitmarkd functions without extra dependencies.

Besides, the local chain should be working with bitcoin/litecoin regression test mode. There are 3 modes of running payment modules: `p2p`, `discovery`, `rest`. Currently, the p2p mode can't be tested in the local chain because it automatically tries to connect to DNS seeds of bitcoin and litecoin for peer discovery on either mainnet or testnet.

**Comment by lemonlatte** [comment]
I create a PR https://github.com/bitmark-inc/bitmarkd/pull/103 to support payments in regression mode. The `regtest` mode of currency blockchain will pin to the `local` chain of bitmarkd. Another config key `bootstrap_nodes` is added to support customized bitcoin / litecoin nodes

**Comment by jamieabc** [comment]
The PR of #111 changes behavior of hashing. When chain is `local`, `bitmarkd` doesn't need `recorderd` to generate hash for a block, `bitmarkd` receives any `nonce` from a internal nonce generator and skips checking.
