### ISSUE TITLE
Disable payment verification for non-mining nodes

### ISSUE THREAD

**Issue by nodestory** [bitmark-inc/bitmarkd#105]
Non-mining nodes don't need to verify if fees for bitmark transactions are already paid or not. The status of a transaction can go to `confirmed` directly from `pending`. Disabling the payment module can remove additional dependencies on bitcoin and litecoin nodes and also reduce network bandwidth usage.

**Comment by hxw** [comment]
I think this can be divided into two stages:

- [x] 1. add a "noverify" setting to the mode. Its only effect is to exit the payment/setup.h:Initialise function without starting ant background processes.  This works but is not committed yet.
- [ ] 2. remove all discovery code.  This need a bit more work to make sure all related code is removed without affection rest or p2p modes

**Comment by nodestory** [comment]
The second item will be tracked in #151.
