### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nodestory** [bitmark-inc/bitmarkd#112]
Starting from 0.12, it seems that there is a memory leak in bitmarkd.

**Comment by jamieabc** [comment]
Memory growing behavior comes from 2 reasons:

1. When using third party library connect to crypto network, it default assumes connection will success and have retry pretty fast, thus causes some memory like in socket level.

2. Go's memory optimization strategy has changed somehow in newer version, it now defaults to preserve as many memory as possible, causes memory usage is high on some high memory machine. Some offices nodes runs in `jail`, which defaults that each container can see all memory of the system, thus each node has wrong assumption of usable memory, when OS cannot provide that much memory to each node, crash happens.

**Comment by hxw** [comment]
o.12.4 deployed
