### ISSUE TITLE
Regression network can't reach consensus

### ISSUE THREAD

**Issue by nodestory** [bitmark-inc/bitmarkd#129]

**Comment by hxw** [comment]
two problems in bitmarkd also hinder this:

1. payments are forgotten as soon as a record is verified, so resubmitting a record after a fork recovery requires another payment
2. free issue proofs are made invalid after a fork recovery

**Comment by pieceofr** [comment]
Add a temporary solution on PR#134 (https://github.com/bitmark-inc/bitmarkd/pull/134)
for regression test, use local_use_internal_hash=true only for one node.
