### ISSUE TITLE
Missing shared library from executing the Bitmark executable

### ISSUE THREAD

**Issue by PirosB3** [bitmark-inc/bitmarkd#4]
While running Bitmark Linux version I come across this issue:

```
root@moby:~/bitmark-0.0.7-linux# ./Bitmark
./Bitmark: error while loading shared libraries: libgmodule-2.0.so.0:
```

It looks like it cannot find the shared objects, which are not in any of the dependencies

**Comment by hxw** [comment]
no dependency problems after update to go.mod
