### ISSUE TITLE
Some dependencies require compiling shared libraries and headers to be present

### ISSUE THREAD

**Issue by PirosB3** [bitmark-inc/bitmarkd#6]
bitmarkd relies on `go-libucl`, and `go-argon2`.

`libucl` is installed by running the `Makefile` in `github.com/bitmark-inc/go-libucl` and moving the headers and shared libs in the appropriate spaces.

`libargon2` is installed by updating the submodules of `go-argon2` and running the `Makefile`.

Installing these 2 libraries required some debugging and could ideally be automated to lower the bar for new users.

**Comment by hxw** [comment]
libucl dependency has been elimiated
libargon2 has beent ported to FreeBSD and Ubuntu
